import pickle

malaytoxicdict={
    "anjing", 
    "babi", 
    "babi bunting", 
    "bahalul", 
    "bahlul", 
    "bangang", 
    "bangsat", 
    "barua",
    "bastard", 
    "bengong", 
    "binatang", 
    "bodoh", 
    "bodoh kimak lancau sial", 
    "bodoh piang",
    "bohsia",
    "bongok", 
    "butoh", 
    "celaka", 
    "cina babi",
    "cibai", 
    "cilaka", 
    "cipap",
    "eh butoh uh babi", 
    "fuck", 
    "fuk",
    "fak",
    "fagot",
    "gila", 
    "haramjadah", 
    "hawau", 
    "indon bangsat",
    "izznur isap pelir",
    "jalang", 
    "kepala bana", 
    "kepala bapak kau", 
    "kepala bapak ko",
    "kepala buto kau", 
    "kepala hotak kau",
    "kepala otak ko",
    "keling", 
    "kontol", 
    "lahanat", 
    "lancau", 
    "lanjau",
    "mak hang belen",
    "mak kau hijau", 
    "mak ko hijau", 
    "mati kau", 
    "melayu bodoh", 
    "mampus", 
    "padan muka",
    "pantat", 
    "pantik", 
    "peliwat", 
    "penipu", 
    "pengkhianat", 
    "pergi mampus", 
    "puki",
    "pukimak", 
    "pukimak hijau", 
    "pundek", 
    "setan", 
    "sohai",
    "shit", 
    "sial", 
    "sundal", 
    "syaitan",
    "syaiton", 
    "tinja",
    "anjing bangang",
    "babi hutan",
    "babi jahanam",
    "babi kencing",
    "bangsat sial",
    "bedebah",
    "bengap",
    "biadab",
    "bodo",
    "bodoh sial",
    "butoh sial",
    "cabul",
    "cacat",
    "cacing tahi",
    "celaka bangsat",
    "cibai betul",
    "congkak",
    "dajal",
    "dungu",
    "goblok",
    "haram",
    "haram jadah",
    "homo",
    "hotak babi",
    "iblis",
    "idiot",
    "jahil",
    "janin babi",
    "kacang hantu",
    "kafir",
    "keling pariah",
    "kentut",
    "keparat",
    "kera",
    "kera hutan",
    "khinzir",
    "kimak",
    "konek",
    "kontol bengkok",
    "kunyuk",
    "laknat",
    "laknatullah",
    "lembap",
    "lesbian",
    "lonte",
    "makan tahi",
    "mak kau bodoh",
    "mak kau bongok",
    "mak kau lancau",
    "mamak",
    "mampus kau",
    "mandul",
    "mangkuk ayun",
    "mengkarung",
    "munafik",
    "najis",
    "neraka",
    "otak babi",
    "otak udang",
    "palatao",
    "pantat busuk",
    "pariah",
    "pepek",
    "perempuan murahan",
    "perogol",
    "pondan",
    "prostitute",
    "puaka",
    "pukimak sial",
    "puta",
    "putar alam",
    "rasis",
    "sakai",
    "sampah",
    "sangkut",
    "sialan",
    "sial betul",
    "sial kau",
    "sombong",
    "spesis babi",
    "sperma babi",
    "sperma haram",
    "syaiton laknat",
    "tak guna",
    "tahi",
    "tahi anjing",
    "tahi kucing",
    "tahi muka",
    "talampau",
    "telanjang",
    "tempang",
    "tolol",
    "tolon",
    "tulang mampus",
    "ulamak mampus",
    "umpan neraka",
    "unta bapak kau",
    "wak lu"
}